### ISSUE TITLE
Build issue for older SoCs

### ISSUE THREAD

**Issue by twwn** [rany2/openwrt#1]
### Describe the bug

Could you please make the (four) wed patches conditional on mt7622≤? Older SoCs like my mt7621 lack hardware support, which causes the build to fail since the compiler wants the relevant `mtk_wed_*` members, but for them that struct is only an empty dummy.

Seems fine as long as I delete these patches.

(Apart from me seeing that with 2+ SSIDs there's some kind of race on 5GHz that allows only one of them to become active ~90% of the time. The other is just reported as "not associated". No such issue on 2.4GHz. Not sure whether that issue is a general mt76, though.)

Thanks for the repo!

### OpenWrt version

git

### OpenWrt release

git

### OpenWrt target/subtarget

ramips

### Device

Tenbay T-MB5EU v01

### Image kind

Self-built image

### Terms

- [X] I am reporting an issue for OpenWrt, not an unsupported fork.

**Comment by rany2** [comment]
> Could you please make the (four) wed patches conditional on mt7622≤? Older SoCs like my mt7621 lack hardware support, which causes the build to fail since the compiler wants the relevant mtk_wed_* members, but for them that struct is only an empty dummy.

Fixed, thanks for reporting!

> (Apart from me seeing that with 2+ SSIDs there's some kind of race on 5GHz that allows only one of them to become active ~90% of the time. The other is just reported as "not associated". No such issue on 2.4GHz. Not sure whether that issue is a general mt76, though.)

I've seen that issue on mt7915 DBDC on mt7621 but it occurs on main OpenWRT as well. Don't know how to help, sorry.

**Comment by twwn** [comment]
Thanks again. I was previously using ptpt52's [mt76 branch](https://github.com/openwrt/mt76/compare/master...ptpt52:mt76:master) and while I don't think it affected much on my devices, the ["phy mac unique"](https://github.com/openwrt/mt76/commit/0c47f2b479545d8285e8e9b3e440a57e9502038a) patch one seemed interesting.
